version: 0.2

env:
    variables:
#        ROOT_DIR : ./build/zzeng
        ARARN_CSR_CRT: arn_zz1
        ENV : test02

phases:
    pre_build:
        commands:
          - echo "zzeng-001-pre_build"
    post_build:
        commands:
          - echo "zzeng-001-post_build"
          - docker build --build-arg SOME_CONDITION=true -t zzeng02-t .

artifacts:
  files:
    - ./Dockerfile
    - ./build/zzeng/taskdef_${ENV}.json
