version: 0.2

env:
    variables:
        ROOT_DIR : ./z_root_ap
        ARARN_CSR_CRT: arn_zz1
        ENV : test02

phases:
  pre_build:
      commands:
        - echo "zzeng-001"


artifacts:
  files:
    - ./build/zzeng/taskdef_$({ENV}.json